# Generated by Django 4.2.7 on 2023-11-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='grau_de_dificuldade',
            field=models.CharField(choices=[('F', 'facil'), ('M', 'moderado'), ('D', 'dificil')], max_length=10),
        ),
    ]
